version: 4.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: dotnet restore
build:
  publish_wap_xcopy: true
  verbosity: minimal